---
title: Time charts for observed lessons
author: Saurabh Khanna 
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(readxl)
```

# Time charts
## Reading in data

```{r}
df <-
  tribble(
    ~school, ~teacher, ~act,                     ~time,
    
    "S1",    "T1",     "Warm-up",                4,
    "S1",    "T1",     "Launch",                 9,
    "S1",    "T1",     "Work-time (individual)", 24,
    "S1",    "T1",     "Whole-class discussion", 5,
    "S1",    "T1",     "Transitions",             3,
    
    "S1",    "T2",     "Warm-up",                2,
    "S1",    "T2",     "Launch",                 8,
    "S1",    "T2",     "Work-time (pairs)",      20,
    "S1",    "T2",     "Whole-class discussion", 13,
    "S1",    "T2",     "Transitions",             1,
    
    "S2",    "T1",     "Warm-up",                8,
    "S2",    "T1",     "Launch",                 5,
    "S2",    "T1",     "Work-time (pairs)",      14,
    "S2",    "T1",     "Whole-class discussion", 4,  
    "S2",    "T1",     "Transitions",             7,
    
    "S3",    "T2",     "Warm-up",                12,
    "S3",    "T2",     "Launch",                 11,
    "S3",    "T2",     "Work-time (pairs)",      17,
    "S3",    "T2",     "Whole-class discussion", 20,
    "S3",    "T2",     "Transitions",             4,
    
    "S3",    "T7",     "Warm-up",                9,
    "S3",    "T7",     "Launch",                 10,
    "S3",    "T7",     "Work-time (individual)", 23,
    "S3",    "T7",     "Whole-class discussion", 29,
    "S3",    "T7",     "Transitions",             4
  ) %>%
  bind_rows(
    read_xlsx("data/ml_data.xlsx")
  ) %>%
  arrange(school, teacher) %>%
  mutate(
    act = act %>% fct_inorder() %>% fct_rev(),
    teacher = teacher %>% fct_inorder() %>% fct_rev(),
    curriculum = if_else(school == "S3", "Japan Math", "SFUSD")
  )
```



## Graphs by percentage duration

```{r}
df %>%
  group_by(school, teacher) %>%
  mutate(
   time = time / sum(time)
  ) %>%
  ungroup %>%
  ggplot(aes(teacher, time, fill = act)) +
  geom_col(position = "stack", color = "black") +
  scale_y_continuous(
    breaks = seq(0, 1, 0.2),
    minor_breaks = NULL,
    labels = scales::percent_format(accuracy = 1)
  ) +
  scale_fill_brewer(palette = "Set2") +
  guides(fill = guide_legend(reverse = T)) +
  theme_bw() +
  coord_flip() +
  facet_grid(vars(school), scales = "free_y") +
  labs(
    x = "Teacher",
    y = "Duration (%)",
    fill = "Activity"
  )
```



## Graphs by total duration

```{r}
df %>% 
  ggplot(aes(teacher, time, fill = act)) +
  geom_col(position = "stack", color = "black") +
  scale_fill_brewer(palette = "Set2") +
  guides(fill = guide_legend(reverse = T)) +
  scale_y_continuous(
    breaks = seq(0, 80, 10)
  ) +
  coord_flip() +
  theme_bw() +
  facet_grid(vars(school), scales = "free_y") +
  labs(
    x = "Teacher",
    y = "Duration (minutes)",
    fill = "Activity"
  )
```


## SFUSD  and JM

```{r}
df %>% 
  group_by(curriculum, act) %>% 
  summarize(
    time_mean = mean(time)
  ) %>% 
  mutate(
    time_perc = time_mean / sum(time_mean)
  ) %>% 
  ungroup() %>% 
  ggplot(aes(curriculum, time_perc, fill = act)) +
  geom_col(position = "stack", color = "black") +
  scale_y_continuous(
    breaks = seq(0, 1, 0.2),
    minor_breaks = NULL,
    labels = scales::percent_format(accuracy = 1)
  ) +
  scale_fill_brewer(palette = "Set2") +
  guides(fill = guide_legend(reverse = T)) +
  theme_bw() +
  coord_flip() +
  labs(
    x = "Curriculum",
    y = "Duration (%)",
    fill = "Activity"
  )
```


